name: Update CV from Overleaf

on:
  workflow_dispatch: # Allows you to run it manually
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight

jobs:
  update_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download PDF from Overleaf
        run: |
          curl -L "https://www.overleaf.com/docs?snappy=true&projectid=68b1f67167aac43dded7f387" -o files/cv.pdf

      - name: Commit and Push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add files/cv.pdf
          git commit -m "Automated CV update from Overleaf" || exit 0
          git push
